CapsAdmin/pac3

- lua/pac3/core/shared/modifiers/model.lua
Fixes the Clockwork fix, capital letters are a bitch.
> Fix Clockwork Fix

- lua/pac3/editor/client/panels/browser.lua
- lua/pac3/editor/client/spawnmenu.lua
> PAC3 settings tab

- lua/pac3/core/client/parts/material.lua
- lua/pac3/editor/client/tools.lua
Editors rewriting whitespace kills me inside.
> Patch add submaterials

- lua/pac3/core/client/hooks.lua
- lua/pac3/core/client/parts/entity.lua
- lua/pac3/editor/client/config.lua
Bugs: Doesn't work if in first person
> Experimental: Hide death ragdoll

- lua/pac3/core/server/netmessages.lua
> Add check to collision group exploit.

- lua/pac3/core/client/parts/custom_animation.lua
- lua/pac3/editor/client/tools.lua
> Patch custom animation part stuff

- lua/pac3/core/client/netmessages.lua
- lua/pac3/core/client/parts/flex.lua
- lua/pac3/core/server/netmessages.lua
My interactive rebase decided it wanted to keep the comments, for some reason.
> Patch add flex part

- lua/pac3/core/client/parts/event.lua
Added randint, allows you to specify on random a min and a max
Added random_timer event - A timer that triggers between a min and a max for x time.
ballsssssssssssssssssssssss
Fixed health_lost , randomly worked sometimes, the event was getting triggered too fast, din't let parents trigger. Had to add a manual cooldown, works now.
Added owner_alive - Checks if the owner is alive or not
> Fixed health_lost, added a few more events

- lua/pac3/editor/client/config.lua
See https://github.com/CapsAdmin/pac3/pull/139
> fix default part icon

- lua/pac3/core/client/hooks.lua
- lua/pac3/core/client/netmessages.lua
- lua/pac3/core/client/parts/entity.lua
- lua/pac3/core/client/parts/ogg.lua
- lua/pac3/core/client/parts/webaudio.lua
- lua/pac3/core/client/util.lua
- lua/pac3/core/shared/modifiers/model.lua
- lua/pac3/core/shared/modifiers/size.lua
- lua/pac3/core/shared/projectiles.lua
- lua/pac3/editor/server/util.lua
Preparing for merge into upstream. Comment if someone notices any bad code. Merging tomorrow, trying to test first. The merge was pretty straightforward conflict free.
Major fixes include player size partial rewrite to fix various bugs (may introduce new ones, tested on metastruct for weeks though)
> Caps merge test

- lua/pac3/editor/client/settings.lua
Affects some custom playermodels (if using the proportions method)
> Change tpose sequence from ragdoll to reference

- lua/pac3/editor/client/examples.lua
Many people ask me about this so it's better to have an example then trying to explain it.
> Add sound replacement example

- lua/pac3/core/client/libraries/urlobj/urlobj.lua
- lua/pac3/core/client/libraries/urltex.lua
- lua/pac3/core/client/libraries/webaudio/streams.lua
- lua/pac3/core/client/parts/custom_animation.lua
- lua/pac3/core/client/parts/ogg.lua
- lua/pac3/core/client/parts/webaudio.lua
- lua/pac3/core/client/util.lua
- lua/pac3/core/shared/init.lua
- lua/pac3/editor/client/saved_parts.lua
And makes it unnecessary to do dropbox URL mangling by hand anymore
> Fixup URLs in single location (fixes dropbox)

- lua/pac3/editor/client/panels/mat_browser.lua
- lua/pac3/editor/client/panels/properties.lua
- Toolgun seperate tab
- Can browse for other materials not listed
- Updated look
- Favorites tab
> Better material browser.

- lua/pac3/editor/client/panels/mat_browser.lua
- lua/pac3/editor/client/panels/properties.lua
Reverts CapsAdmin/pac3#290
"Flex: I just now found out the mat browser doesnt work"
> Revert "Better material browser."

- lua/pac3/editor/client/tools.lua
Output turns from this:
To this:
> Overhaul of the output when converting to E2 holograms.

- lua/pac3/editor/client/tools.lua
http://i.imgur.com/OgNtgeJ.jpg
> Fixing indenting on E2 output for converting to E2

- lua/pac3/editor/client/tools.lua
Clipping somewhat working but commented for now.
> Fix E2 format, Attempt at fixing clipping

- lua/pac3/core/client/parts/sound.lua
Fixes #414
i found this useful
> Play to local player only

- lua/pac3/editor/server/wear.lua
> pac_request_outfits cooldown instead of blocking pac_request_outfits

- lua/pac3/core/client/bones.lua
this will ease the pain of coders who rely on player bones in their addons
> Call PACResetBones hook on bone reset

- lua/pac3/core/client/libraries/urltex.lua
- lua/pac3/core/client/parts/sprite.lua
- lua/pac3/core/client/util.lua
Also added additionalData argument to url function
And fixed urltext Queue is ignoring shader passed to GetMaterialFromURL
Fixes #431
> Fixed Sprites materials by URL

- lua/pac3/editor/client/view.lua
Fixes #430
Also i think this can be now enabled by default
> Fixed camera follow mode

- lua/pac3/core/client/init.lua
not tested but I guess it will work
> use a clientside hook

- lua/pac3/editor/client/panels/editor.lua
> Revert "Re-Add close button"

- lua/pac3/core/client/parts/event.lua
- lua/pac3/editor/client/panels/properties.lua
For modders who want to add custom events in PAC3
Will be merged after more tests.
> Events API

- lua/pac3/editor/client/tools.lua
Updated and slimmed down the output expression2 code.
The previous code outputted was very high on line count for little gain.
It's now a lot more slim and easier to read as well as edit.
vs
> Updating tools.lua's convert to holograms.

- lua/pac3/core/client/util.lua
not sure if there are any more new subdomains now.
> dl.dropbox.com support for fixupurl

- lua/pac3/editor/client/tools.lua
Fixing issues I overlooked (indexing, angling and parent bases).
> Fixing issues with holo-conversion tools.lua

- lua/pac3/core/client/parts/webaudio.lua
Fix webaudio sounds playing before their position is set. Also make webaudio sounds play after they're loaded if they should be playing.
> Fixes to webaudio

- lua/pac3/core/client/hooks.lua
it got renamed to pacx I believe.
> maybe fix serverside playerscaling

- lua/pac3/libraries/urlobj/urlobj.lua
`IMesh:BuildFromTriangles` in GMod's dev branch can write userdata to mesh vertices now. If you want bumpmaps to work, put the tangent data in there.
This is more of an example than a pull-request and doesn't do anything fancy like yielding the coroutine. Important bit is line 617.
> write tangent userdata to urlobj meshes for bumpmaps

- lua/pac3/core/client/part_pool.lua
RenderView was causing PAC Rendering to be fucky
> Fix issue w/ RenderView

- lua/pac3/core/client/parts/bone.lua
- lua/pac3/core/client/parts/bone2.lua
This is going to break a lot of pacs that use followpart but they were technically already broken. I'd make sure this is the behavior we want before merging though.
Fixes https://github.com/CapsAdmin/pac3/issues/571
> Fix followpart using euler angle addition for following bones.

- lua/pac3/core/client/base_part.lua
https://github.com/Facepunch/garrysmod-issues/issues/3396
> Turn off blend-override until its fixed

- lua/pac3/core/client/init.lua
- lua/pac3/core/client/part_pool.lua
this obfuscates and randomizes upvalues
> obsfucate part_pool.lua at runtime

- lua/pac3/editor/client/tools.lua
New hologram system allows dynamic spawning of holograms so the holograms will spawn regardless of server settings for burst rate, burst limit, etc bar max hologram limit.
Also allows for future implementation of having multiple files included that contain hologram data for easy seperation of hologram from spawning and running. 
New format also maximises space use and makes navigating larger files with many holograms less intensive.
> Semi-rewrite to implement new hologram spawning system + cleanup

- lua/pac3/editor/client/tools.lua
Implemented new features to parts > holograms such as separation of local entity and parent entity. Added documentation. Cleaned up tools.lua for consistency.
Questions regarding line 200 on tools.lua with the tool "round numbers" and its unused functions. Are they used for anything? Does this tool still work as it seems to not work.
> Implementation of new features to parts > holograms + cleanups to tools.lua

- lua/pac3/editor/client/asset_browser.lua
Adds GUI controls to the Resource browser to handle zooming, to work alongside the current hot keys.
This is to contribute towards resolving issue #521
> Resource Browser GUI zoom controls

- lua/pac3/editor/client/panels/properties.lua
General [color editor improvements](https://github.com/CapsAdmin/pac3/projects/1#card-9172487) 
- Allows easier copy/pasting of colors
- Fixes conversion of rgb to hex values
- Supports pasting of both #fff and #ffffff
- Only updates when changed instead on Think hook
[Gif of editor in use](https://i.imgur.com/XIj8yyY.gif)
> Color Editor Improvements

- lua/pac3/editor/client/panels/editor.lua
- lua/pac3/editor/client/view.lua
Should help the 2 people in the community that actually use this feature. :)
> Made the FOV/zoom slider actually visible.

- lua/pac3/core/client/parts/material2.lua
- lua/pac3/libraries/shader_params.lua
> Some refract shader changes. 

- lua/pac3/editor/client/animation_timeline.lua
- lua/pac3/editor/client/panels/editor.lua
- lua/pac3/editor/client/panels/tree.lua
- lua/pac3/editor/client/view.lua
Zoom settings include persistent zoom, zoom on mouse wheel and smooth zooming.
> Zoom slider settings and some small fixes

- lua/pac3/libraries/webaudio.lua
double )), caused error on load
> Fix typo in webaudio panic fix

- lua/pac3/editor/client/view.lua
Maybe explains by itself... *cough* fix for zoomslider https://github.com/CapsAdmin/pac3/pull/807
> Check if the editor is valid

- lua/pac3/core/client/part_pool.lua
> fix pac_sv_hide_outfit_on_death

- lua/pac3/editor/client/wear.lua
- lua/pac3/editor/server/wear.lua
should fix #831 and other issues related to wearing or filter issues.
Not sure why it was changed to number but UIDs are fairly long and would overflow in some cases.
I tested this on the pac server and it seemed to work fine but in case I missed something please do tell me.
> change from number to string

- lua/pac3/core/client/integration_tools.lua
- lua/pac3/core/client/part_pool.lua
> Make sure entity is actually removed

- lua/pac3/core/shared/util.lua
> Fallback to ingame model if zip doesn't contain it

- lua/pac3/core/shared/util.lua
> Started mdl corruption fix

- lua/pac3/core/client/part_pool.lua
- lua/pac3/editor/client/wear.lua
> Made render time limit disable entity's parts until reworn.

- lua/pac3/core/client/parts/text.lua
This should fix text which got cutoff.
> Fix text getting cut off

- lua/pac3/core/client/parts/event.lua
Maybe fixes: #911
Not sure why the code wasn't this, but will check more in depth later.
> Just return precalculated enums

- lua/pac3/core/client/parts/custom_animation.lua
rather have my console spammed than my screen spammed
> custom_animation: Derma_Message -> print on fetch error

- lua/pac3/core/shared/util.lua
> Add "models/" to the .ani path.

- lua/pac3/core/shared/init.lua
- lua/pac3/core/shared/util.lua
- lua/pac3/editor/client/wear.lua
- lua/pac3/editor/server/wear.lua
- lua/pac3/libraries/net_stream.lua
- lua/pac3/libraries/string_stream.lua
This is not 100% yet, there's currently an infinite loop in mdlzip functionality.
> Port over the new StringStream and net streaming functionality from starfall

- lua/autorun/netstream.lua
- lua/pac3/core/shared/init.lua
- lua/pac3/editor/client/wear.lua
- lua/pac3/editor/server/wear.lua
https://github.com/wiremod/advdupe2/pull/358
https://github.com/thegrb93/StarfallEx/pull/1085
https://github.com/CapsAdmin/pac3/pull/999
> Move netstream to lua/autorun

- lua/pac3/core/client/parts/model.lua
- lua/pac3/core/shared/util.lua
- lua/pac3/editor/client/tools.lua
Just noticed that forceobj does not work on SetModel in most cases, so this is not only [convertation issue](https://github.com/CapsAdmin/pac3/issues/1066). Guess because meta vars is not full loaded at that moment. Anyway there is a some better way to do typechecks and make it automated.
> better typecheck

- lua/pac3/core/client/parts/event.lua
- lua/pac3/editor/client/init.lua
- lua/pac3/editor/client/panels/editor.lua
- lua/pac3/editor/client/panels/properties.lua
- lua/pac3/editor/client/shortcuts.lua
> Editor fixes

- lua/pac3/core/shared/util.lua
> use full material path instead of name when needed

- lua/pac3/editor/client/animation_timeline.lua
- lua/pac3/libraries/animations.lua
Adds support for setting [easing styles](https://github.com/CapsAdmin/pac3/pull/1106#issue-1051092992) directly in the animation editor.
> Editor support for easing styles

- lua/pac3/core/client/bones.lua
- lua/pac3/core/client/integration_tools.lua
- lua/pac3/core/client/part_pool.lua
- lua/pac3/core/client/parts/legacy/entity.lua
- lua/pac3/core/client/parts/legacy/model.lua
- lua/pac3/core/client/parts/model.lua
- lua/pac3/core/client/parts/model/weapon.lua
- lua/pac3/core/client/parts/motion_blur.lua
- lua/pac3/editor/client/animation_timeline.lua
- lua/pac3/editor/client/tools.lua
- lua/pac3/editor/client/view.lua
Maybe fixes: #1235 
Not sure if its the correct solution though
> Fix setupbones infinite loop

- lua/pac3/core/client/parts/legacy/sound.lua
- lua/pac3/core/client/parts/sound.lua
"Sequential" tickbox makes listed sounds go in order instead of randomly, with steps to go forward, backward, stay in place or skip items.
Should work with both the semicolon separator and [min,max] bracket substitutor/expander notations
Also regrouped generic properties in relevant categories (generic and playback)
And gave sound2 PlayCount an editor_friendly that tells the user they can set it to 0 to loop
> sequential playback for legacy sound and websound parts (sound, sound2)

- lua/pac3/extra/shared/hands.lua
I've changed the Hands SWEP to not be so cursed whilst adding the ability to do something with the viewmodel in pac.
> Hands SWEP changes

- lua/pac3/core/client/part_pool.lua
- lua/pac3/core/client/parts/damage_zone.lua
- lua/pac3/core/client/parts/event.lua
- lua/pac3/core/client/parts/force.lua
- lua/pac3/core/client/parts/health_modifier.lua
- lua/pac3/core/client/parts/hitscan.lua
- lua/pac3/core/client/parts/lock.lua
- lua/pac3/core/client/parts/movement.lua
- lua/pac3/core/client/parts/projectile.lua
- lua/pac3/core/client/parts/proxy.lua
- lua/pac3/core/shared/movement.lua
- lua/pac3/editor/server/bans.lua
- lua/pac3/editor/server/combat_bans.lua
- lua/pac3/editor/server/init.lua
- lua/pac3/editor/server/pac_settings_manager.lua
- lua/pac3/extra/shared/init.lua
- lua/pac3/extra/shared/net_combat.lua
- lua/pac3/extra/shared/projectiles.lua
for a provisory feature list, see the readme on my repository https://github.com/pingu7867/pac3
I had to split my main branch into three for ease of review, but it's still a big task and all three parts are still related. So we will not be merging until all three are approved. Let's take our time.
> The Combat Update. Part 1 : the combat stuff

- lua/pac3/core/client/parts/camera.lua
- lua/pac3/core/client/parts/command.lua
- lua/pac3/core/client/parts/group.lua
- lua/pac3/editor/client/asset_browser.lua
- lua/pac3/editor/client/fonts.lua
- lua/pac3/editor/client/init.lua
- lua/pac3/editor/client/logic.lua
- lua/pac3/editor/client/menu_bar.lua
- lua/pac3/editor/client/panels/editor.lua
- lua/pac3/editor/client/panels/extra_properties.lua
- lua/pac3/editor/client/panels/pac_tree.lua
- lua/pac3/editor/client/panels/properties.lua
- lua/pac3/editor/client/panels/tree.lua
- lua/pac3/editor/client/parts.lua
- lua/pac3/editor/client/popups_part_tutorials.lua
- lua/pac3/editor/client/saved_parts.lua
- lua/pac3/editor/client/settings.lua
- lua/pac3/editor/client/shortcuts.lua
- lua/pac3/editor/client/spawnmenu.lua
- lua/pac3/editor/client/tools.lua
- lua/pac3/editor/client/view.lua
for a provisory feature list, see the readme on my repository https://github.com/pingu7867/pac3
I had to split my main branch into three for ease of review, but it's still a big task and all three parts are still related. So let's take our time.
> The Combat Update. Part 2 : the editor stuff

- lua/pac3/core/client/parts/damage_zone.lua
- lua/pac3/core/client/parts/force.lua
- lua/pac3/core/client/parts/health_modifier.lua
- lua/pac3/core/client/parts/hitscan.lua
- lua/pac3/core/client/parts/lock.lua
if combat parts are deactivated, instead use part label's SetError function to tell users about it instead
and two minor fixes on damage zone
> suppress network string errors

- lua/pac3/extra/shared/net_combat.lua
- lua/pac3/extra/shared/projectiles.lua
Adds a check to the healing function of damaging parts to make sure the target's health/armor isn't already over max health/armor.
> Prevent healing functions from removing overheal

- lua/pac3/extra/shared/hands.lua
This just makes the hands weapon look a little bit nicer in the spawnmenu.
> Add spawnmenu icon to hands SWEP
