CapsAdmin/pac3

lua/pac3/core/client/parts/ogg.lua

false positive a lot of the time and spammy. You guys should really use
the webaudio part instead of the ogg part anyway
Conflicts:
lua/pac3/core/client/parts/ogg.lua

silence error

---

lua/pac3/editor/client/config.lua

Add a hook that runs at the bottom of pace's config.lua so that custom
parts can setup their editor config (location in tree, icon, etc) at the
appropriate time

Add hook for pac editor config

---

lua/pac3/editor/client/tools.lua

SetSubMaterial support is gone from this repo, so why even keep the tool in the editor?

Removed Dump SubMaterials

---

lua/pac3/editor/server/global_bans.lua

The end of the string ]] on line 17 was being interpreted as the end of the comment block, so the rest of the file was being parsed and erroring.

Fix comment format in global_bans.lua

---

lua/pac3/editor/client/tools.lua

I wrote this pac editor tool ages ago to assist with manual bone merging, but just realized it wasn't doing everything it should. 
With this PR, new dummy bones created by this tool also:
* Follow the bone they are acting as a dummy of (how did I miss this?)
* Have a name suffixed with `_dummy` to keep follow parts unambiguous
For reference to future readers, to use these tools to do a manual model-to-player bonemerge, just:
*  Create a group for the dummy bones and click on it in the tree
*  Click on tools -> populate with dummy bones
*  Add the model you want to bonemerge to your player to the root group
*  Set your model bone to "invalidbone" so it shares its origin with the player model's
*  Click your model and hit tools -> populate with bones
*  For each bone in your model, set its …

Make the editor tool "populate with dummy bones" useful

---

lua/pac3/editor/client/panels/properties.lua

After recent GMod update, the buttons for selecting and stuff broke. Adding a 1 tick timer fixes this.

[...] button fix

---

lua/pac3/editor/client/init.lua

Checks that the hook identifier is a string before running substring on it

Fix pace.Restore/DisableExternalHooks not handling entity hooks properly

---

lua/pac3/core/client/drawing.lua

This should resolve pain for many coders when they are using ply:SetNoDraw(true) (for example, spectator or ghost, or when player enters vehicle what hides player).
Tested on our server for a long time.

GetNoDraw() for hiding PAC when player is not drawn

---

lua/pac3/core/client/drawing.lua
lua/pac3/core/client/integration_tools.lua
lua/pac3/core/client/parts/model.lua

In 2D contexts such as Derma Panels using Pop/PushFlashlightMode leads to crashes, this fixes these crashes. 
Please ignore the whitespace in the diffs, my editor removes tabs and whitespace on empty lines.

Disable flashlight in 2d context to avoid crashes

---

lua/pac3/editor/server/wear.lua

So, any attempt from players to break wear on server will fail
This fixes the case where player is trying to send very big outfit that
crashes wear on serverside

xpcall in wear timer

---

lua/pac3/editor/client/config.lua
lua/pac3/editor/client/panels/editor.lua
lua/pac3/editor/client/parts.lua
lua/pac3/editor/client/saved_parts.lua
lua/pac3/editor/client/translations/russian.lua

Make `Copy` works like `Clone`, but with auto parent to selected part
Don't populate `Backups` after `Load` was hovered, and moved `Backups` to bottom of menu
Hide `DFrame` useless panels in PAC3 Editor Panel

Menu improvements

---

lua/pac3/editor/client/panels/editor.lua

It now doesn't hide and doesn't call MakePopup(); so code of any quality now should work with it (no more menu closing on MetaStruct); And enabled old close button, but made it invisible

Re-Add close button[2]

---

lua/pac3/core/client/hooks.lua
lua/pac3/core/client/parts/model2.lua

Probably not the best way.
Is there a part hook for when an entity part's owner is changed? I think that should be used instead of OnShow/OnRemove

Preserve entity model after PVS update and reset model when entity part is removed.

---

lua/pac3/core/client/base_part.lua

Haven't tested yet but should be good, I'll leave here anyway to see if anyone has suggestions. I don't see any immediate issues with the pipeline so I'm assuming its a gmod multicore bug, but might need to look deeper into how translucent parts work.

Translucent parts don't play nicely with blend override.

---

lua/pac3/core/client/part_pool.lua

To fix this error:
```
[ERROR] addons/pac3-master/lua/pac3/core/client/part_pool.lua:44: Player is NULL(!?)
1. UniqueID - [C]:-1
2. parts_from_ent - addons/pac3-master/lua/pac3/core/client/part_pool.lua:44
3. fn - addons/pac3-master/lua/pac3/core/client/part_pool.lua:393
4. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:110
```

part_pool: Check for null owner in OnEntityCreated

---

lua/pac3/editor/client/saved_parts.lua

`ERR: lua/pac3/editor/client/saved_parts.lua:66: bad argument #2 to 'Time' (string expected, got no value)`

add depot to file.Time to fix error

---

lua/pac3/core/client/parts/physics.lua

Re-applies gravity setting when physics object is recreated
This fixes issue [#708](https://github.com/CapsAdmin/pac3/issues/708)

Gravity fix

---

lua/pac3/core/client/parts/beam.lua

Fixes the regex used in beam PART:GetNiceName to allow the use of custom materials on beam parts
This fixes issue [#711](https://github.com/CapsAdmin/pac3/issues/711)

Regex fix for GetNiceName

---

lua/pac3/core/client/parts/bone.lua

Disables the functionality of the hide mesh property of the bone part, until a complete fix can be found. 
When this hide mesh property is enabled on the bone part, if the player dies, depending on the bone its linked to, it can cause the physics engine to throw unhandled exceptions, completely hang the hl2 process, and other undefined behaviors. This could be very destructive as players can enter servers with Pac3 and cause all players nearby to crash, with minimal effort.
This is caused by setting the bone scale to scale_inf which is a vector with math.huge in x,y and z. This somehow becomes a problem for the engine when the player dies. It may be possible to reset the scale of the bones just before the player is turned into a rag doll but I haven't been able to come up with a solution …

Disable Bone HideMesh functionality to prevent crashes

---

lua/pac3/editor/client/panels/extra_properties.lua

Resets the material of the viewer to white, when hovering over an unset texture property. 
This fixes: #698

Reset mat viewer when hovering on unset texture property

---

lua/pac3/libraries/netx.lua

Fixes issue #756 
When strings which are also valid integers are used as names, they are converted to TYPE_NUMBER_UID mistakenly, causing string properties to be converted into numbers
The fix prevents any strings that are longer than 1 character and begin with 0, from being converted

Prevent 0 prefixed strings becoming numbers

---

lua/pac3/core/client/parts/flex.lua

Added a description to the RootOwner property, to prevent confusion
Changed the default value of RootOwner to false, to match the functionality of other parts
This is to help prevent confusion as seen with issue #749

Improved description of flex property RootOwner

---

lua/pac3/core/shared/http.lua

During my digging trough the Logs i have discovered this error.
```
[ERROR] lua/includes/extensions/string.lua:261: attempt to compare nil with number
1. NiceSize - lua/includes/extensions/string.lua:261
2. unknown - addons/pac3_dev/lua/pac3/core/shared/http.lua:108
```
'len' is not existing, so it must be 'length'?

Not supposed to be 'length'?

---

lua/pac3/editor/client/shortcuts.lua

During my digging trough the Logs i have discovered this error.
```
[ERROR] addons/pac3_dev/lua/pac3/editor/client/shortcuts.lua:4: attempt to call field 'SavePartToFile' (a nil value)
1. Call - addons/pac3_dev/lua/pac3/editor/client/shortcuts.lua:4
2. nextevent - addons/pac3_dev/lua/pac3/editor/client/shortcuts.lua:24
3. unknown - lua/dlib/modules/hook.lua:1067
```
`pace.SavePartToFile()` Does not seem to exist, also not in the source code. So then `pace.SaveParts()` is used, but I'm not 100% sure if it's meant to be used like that. It seems that `pace.SavePartToFile()` only saves the selected part and not all parts.
Besides, is CTRL + M not intended as a kind of quicksave?

Fixed Save Shortcut

---

lua/pac3/editor/client/shortcuts.lua

Make some shortcuts available only if the editor is in the foreground,
This should prevent e.g. the accidental saving during the free view.

Some changes to shortcuts

---

lua/pac3/core/client/bones.lua

This lets players disallow outfits from using the local player's `EyePos()` and `EyeAngles()` with the cvar `pac_allow_camera_bone`

Added CVar to opt-out of using 'camera' and 'player_eyes' as a bone

---

lua/pac3/libraries/webaudio.lua

[PAC3-Server/notagain@5aa7f21](https://github.com/PAC3-Server/notagain/commit/5aa7f21084634f3c414f7fff828948a914d553b9)
Fixes error and potential crash on disconnect/map change when webaudio panicked

Webaudio IsValid fix

---

lua/pac3/editor/client/about.lua

Since you can no longer execute this command, it is only unnecessary spam in the (server) console.

the command 'volume' is blocked.

---

lua/pac3/editor/client/menu_bar.lua
lua/pac3/editor/client/panels/properties.lua

It was constantly getting in the way, hiding up to 2-3 characters. I'm supriced nobody did this long ago.

Disabled the language ID indicator

---

lua/pac3/core/client/part_pool.lua
lua/pac3/core/shared/init.lua

So when you spawn with no weapon, you outfit gonna be hidden, becouse it loads only from OnEntityCreated hook from your weapon(s) via GetOwner. There is a fix for it. Also is there reason why hide outfit cvar was removed?

prevent disapearing parts affter death on servers where is no weapon on spawn

---

lua/pac3/core/shared/entity_mutator.lua

While investigating a performance issue on my server, I was looking through some hooks and noticed a ton of PAC hooks on `SetupMove`. After clearing them all, the lag we saw disappeared.
I don't know if removing those hooks actually fixed the performance problems - I certainly don't see anything in here that would be causing problems, but that's my anecdote. (We were experiencing large lag spikes every time the GC collected)
Either way, I don't think the current usage of `SetupMove` is correct.
https://wiki.facepunch.com/gmod/GM:SetupMove
The hook sends 3 parameters, `Player, CMoveData, CUserCmd`.
The existing code expects four arguments, discards one it cares about, and shadows `ply` which is needed for comparison (I _think_)
As a result, the hooks likely never get cleared, and the …

Fix SetupMove usage

---

lua/pac3/core/client/parts/event.lua

I just feel like it looks better that way.

New colors for the event wheel

---

lua/pac3/editor/client/animation_timeline.lua
lua/pac3/editor/client/view.lua

'none' causes cursor flicker and framerate drops (might be hard to notice but on high framerates it's very obvious)

Don't use "none" when setting cursors.

---

lua/pac3/editor/client/saved_parts.lua

Allows preventing clients from loading outfits on themselves via the PAC editor or pac_wear_parts

Added hook to control loading outfits from files and URLs (for local player only)

---

lua/pac3/extra/server/contraption.lua

SetColor is called before the Entity Spawns, which causes this error.
```
Trace:
1: Line 32	"Trace"		lua/includes/extensions/debug.lua
2: Line 40	"nil"		addons/pac3-develop/lua/pac3/editor/server/util.lua
3: C function	"SetColorOriginal4"
4: Line 192	"SetColor"		lua/includes/extensions/entity.lua
5: Line 28	"spawn"		addons/pac3-develop/lua/pac3/extra/server/contraption.lua
6: Line 113	"nil"		addons/pac3-develop/lua/pac3/extra/server/contraption.lua
7: C function	"xpcall"
8: Line 39	"PCallCriticalFunction"		addons/pac3-develop/lua/pac3/editor/server/util.lua
9: Line 56	"func"		addons/pac3-develop/lua/pac3/editor/server/util.lua
10: Line 32	"nil"		lua/includes/extensions/net.lua
```

Move ent:SetColor() in contraption to after ent:Spawn().

---

lua/pac3/core/client/parts/animation.lua

- Rate setting now multiplies playback rate so a Rate of 1 is now actually 1x playback speed
- Fixed divide by 0 when Min and Max settings are the same number (doing this now explicitly sets the progress of the animation)
- Setting Rate to 0 now pauses animation like one would expect instead of also setting the current frame to 0
- Removed rate limit that was sometimes so low that animations could not be played at the original speed
- Made self.frame wrap from 0 to 2 so extremely high rates will never become so high they experience floating point precision loss
- Removed some unnecessary code that never ran
- Replaced some code with more optimized alternatives
- Can now disable looping
Everything has been tested by me

Fixed animation

---

lua/pac3/core/client/parts/shake.lua

A workaround for #1127 
This pretty much creates a fake shake radius by setting amplitude to 0 if the camera distance is higher than the set radius.
Includes optional falloff setting.

scale shake amplitude with distance

---

lua/pac3/core/client/parts/material.lua
lua/pac3/libraries/shader_params.lua

Setting different defaults for each shader now works properly.
The fixed 'load vmt' makes it really easy to replace/edit existing in-game materials.
New defaults create proper materials instead of the old empty/error ones:
The new/fixed params allow users to create materials such as this one:

new material defaults + fixes

---

lua/pac3/extra/client/contraption.lua
lua/pac3/extra/server/contraption.lua

Props should now spawn properly, have correct colors and working transparency. Related to #1078

Fixes for the 'spawn as props' tool 

---

lua/pac3/core/shared/http.lua
lua/pac3/libraries/urltex.lua

Because the URL for this part is injected into an HTML blob, attackers can manually send a malicious part that can run arbitrary javascript code on any client that renders their PAC.
My fix updates the `pac.FixUrl` method to strip out exploitative HTML characters (that aren't valid in URLs anyway), and ensures that the `size` parameter is a number before concatenating it into the HTML blob.
This has been tested on our server and works as expected with no noticeable side effects.
Big thanks to @plally for helping me quickly investigate this.

Fix an HTML injection exploit

---

lua/pac3/editor/client/panels/properties.lua

minus or numpad minus + left clicking on a number (or vector component) will invert the sign between negative and positive
upon right clicking a string property, between paste and reset, a new option, "change sides" will change "right" to "left", or vice versa (but it doesn't work if the property is a part yet)

quality of life: flipping the sign and switching hand sides

---

lua/pac3/core/client/test.lua
lua/pac3/core/server/test_suite_backdoor.lua

Currently anyone with superadmin can run lua code on a server with pac. This isn't the biggest security concern but it'd be best to have another check in place to make sure that anyone that manages to get superadmin cannot run code without it being intentionally toggled on.
And this pr fixes a typo

Backdoor improvements

---

lua/entities/gmod_wire_expression2/core/custom/pac.lua
lua/pac3/core/server/util.lua
lua/pac3/extra/client/wire_expression_extension.lua

This pr adds `pac.RatelimitPlayer` which allows any pac function to easily implement a leaky bucket like ratelimit. The benefit of using a leaky bucket system over a regular system is that it allows more freedom for regular users yet still prevents excessive abuse.
I've implemented this on the e2 core and added convars to disable it. I also added a simple fix for the e2 core as currently players can spam everyones console with lua errors using e2.
The leaky bucket code is a little bit experimental but i couldn't find any issues with it when i tested it.

Add leaky bucket ratelimiting system and use it in e2 core

---

lua/pac3/core/client/owner_name.lua
lua/pac3/core/client/tests/events.lua
lua/pac3/editor/client/about.lua
lua/pac3/editor/client/asset_browser.lua
lua/pac3/editor/client/logic.lua
lua/pac3/editor/client/panels/lua_editor.lua
lua/pac3/editor/client/panels/tree.lua
lua/pac3/editor/client/parts.lua
lua/pac3/editor/client/tools.lua
lua/pac3/editor/client/wires.lua
lua/pac3/libraries/animations.lua

This pr aims to reduce the global table pollution by localizing variables that should've been local.
From:
The tool didn't display all the old globals, but there where more.
To:

Reduce globals

---

lua/pac3/core/server/util.lua

While writing the first-pass of GLuaTest unit tests, I noticed that `pac.RatelimitAlert` might have a bug.
If the given player doesn't have any rate limit data on them at all, it appears that `pac.RatelimitAlert` won't do anything on the first call because it sets the alert to `CurTime() + 3`, which makes it fail the actual ratelimit check.
I believe this is how it was intended to be set up originally - on the first call, it should still send the message.
If this is **not** the case and I missed something, just let me know 👍

Fix first call of RatelimitAlert

---

lua/pac3/core/client/parts/animation.lua
lua/pac3/core/client/util.lua

Before:  
https://user-images.githubusercontent.com/86734639/204056601-d44f08f8-e7f9-492a-bf53-909da7a1d4da.mp4  
After:  
https://user-images.githubusercontent.com/86734639/204056942-acf5d764-d383-4e03-a746-8baf5f741c77.mp4  
Animation parts now use a stack. When PART:OnShow() is called, it stops the current animation if there is one unless the current animation is the same PART, the part becomes the active animation, plays, and moves to the top of the stack. When PART:OnHide() is called, it stops its animation, removes itself from the stack, and plays the animation at the new top of the stack if it was the last one and if the stack is not empty. It's done in a way that will not interfere with anything outside of animation.lua.  
Edit: Forgot to mention, with Pac's current method, it's …

Make animation parts use a stack

---

lua/pac3/core/client/parts/animation.lua

Fixes a bug with [73e8e34](https://github.com/CapsAdmin/pac3/pull/1265/commits/73e8e34dcde5cfdcfbd74684fa5fe6f14b0a8fc3) that causes the animation part to spew errors because of `AnimStack` not existing in the context of `get(self)`.
```lua
local AnimStack = {
__index = {
...
get = function(self)
...
animStack = AnimStack()
...
end
}
}
```

Fix AnimStack not existing in get()

---

lua/pac3/editor/client/spawnmenu.lua

Added autocomplete to pac_wear_parts and removed the need to wrap file names with spaces in quotes.

Add autocomplete to pac_wear_parts

---

lua/pac3/editor/client/panels/editor.lua

Bug: Button events didn't work properly in autoload pacs, before opening the pac editor (using a pac without opening the editor is indeed autoload's main purpose, or one of them at least)
Explanation: Because of this single boolean, the statement at line 1189 of the event part's code resolves to true regardless of whether it's actually true, and the statement skips the necessary lines that update the active buttons. Uninverted button events "worked" because they show stuff when the button is not pressed, so indeed, if no button is recognized then that event will detect the absence and not hide the stuff.
if ply == pac.LocalPlayer and (pace and pace.IsFocused() or gui.IsConsoleVisible()) then return end
Before we open it, the editor is not focused, so it can't be initialized to true. It …

fixing a small bug with autoload and button events

---

lua/pac3/core/client/parts/legacy/entity.lua
lua/pac3/core/client/parts/player_config.lua
lua/pac3/core/shared/footsteps_fix.lua

manually asking the client realm to network the player entity's mute footsteps bool from the client to the server realm
and the server realm then runs a footstep hook to mute

a fix for singleplayer mute footsteps

---

lua/pac3/editor/client/menu_bar.lua
lua/pac3/editor/client/view.lua

added option "enable editor camera" with convar pac_enable_editor_view
added the value of the camera follow as a number in the label to see what state it's at without guessing or testing
it will refresh the view after mouse release
if pac_enable_editor_view = 1 pac will switch views and try to get a camera, otherwise it will take regular EyePos

option to bypass editor's camera

---

lua/pac3/editor/client/wear.lua
lua/pac3/editor/server/wear.lua

What got me started here was a relatively minor bug. I noticed that sometimes when applying a PAC, the message that confirms your part was applied:
```
[PAC3] Your part "blah" has been applied
```
wouldn't run for all of the parts I applied - it missed maybe 2/6 in my tests.
It's not a big deal, but while trying to figure out why, I found some opportunities to improve the current queue system.
The current `StreamQueue` system is set up to [queue a part if a part has already been submitted in the same frame](https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/editor/server/wear.lua#L112-L118). The frame is calculated from [a `0.1`s timer](https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/editor/server/wear.lua#L12-L18) which also runs `SubmitPart` with the queued data.
The problem …

Rework submitpart and streamqueue

---

lua/pac3/editor/client/wear.lua

Will be used for disabling or changing to `autowear_terrortown.txt` so ttt can have different default outfits.

Add hook for autowear

---

lua/pac3/extra/client/wire_expression_extension.lua

There was no way to get the clientside `pac.WorldEntity` in serverside E2. 
This change makes it so that when `world()` is passed into the `pacSetKeyValue()`, it uses `pac.WorldEntity` on the clientside.

Added ability for pacSetKeyValue() E2 function to work on parts with group owner name set to world.

---

lua/entities/gmod_wire_expression2/core/custom/pac.lua
lua/pac3/extra/client/wire_expression_extension.lua

See #1347
- Changed description on `pac_e2_ratelimit_buffer` and `pac_e2_ratelimit_refill` to be more descriptive
- Fixed ratelimit used `GetInt` instead of `GetFloat` causing instant limit hits with values below 1
----
PAC3's E2 functions do not have limits on the amount of data put into them, meaning you can very easily overflow an entire server's clients. This PR adds a limit to this, and also includes small changes to fit modern Wiremod practices.
- Add size limit in bytes for PAC E2 functions, default 2048 bytes, resets every tick
- Replaces `E2Lib.raiseException` with `self:throw()` (functionally identical)
- Removes wrapping vector and angle types (unnecessary for newer version of Wiremod)

Add size limit to E2 functions

---

lua/pac3/core/client/part_pool.lua
lua/pac3/editor/client/init.lua

It will help to reduce the senseless number of player.GetAll() calls and reduce CPU load

Use player.Iterator() instead of player.GetAll() (Development branch)

---

lua/pac3/editor/client/wear.lua
lua/pac3/editor/client/wear_filter.lua

the outfit filters were not working unless you opened the settings menu once, which was weird. 
Also it would not ignore them if you requested outfits from the server.
I made a pr because I'm actually not sure about wear_filter.lua, I found it weird how the config file for it was stored in it's own folder separated from the rest.

fix outfit filters not working

---

lua/pac3/editor/server/bans.lua
lua/pac3/editor/server/combat_bans.lua

Without these checks, anyone can ban anyone or view the server's entire ban list with a little CCE.

Add admin checks to admin networking

---

lua/pac3/editor/client/tools.lua

E2 has a function to invert hologram models, similar to how model parts in PAC3 can be inverted. This adds the invert flag to the converter.

update PAC3 to E2 holo to use invert flag

---

lua/pac3/core/client/parts/bone.lua
lua/pac3/core/client/parts/clip.lua

Resolves last reported problem on issue #1341

Fixed clip planes lagging behind when parented to a bone on a model part

---

lua/pac3/core/client/parts/event.lua

Adds two small event types for convenience

is_no_draw and viewer_steamid events

---

lua/pac3/core/server/effects.lua
lua/pac3/core/shared/init.lua

Blacklist crashing effect
